"""Action model — a decision to deploy a resource to an incident.

Actions are produced by the planner stage.  Each action pairs exactly one
resource with exactly one incident and records the rationale for the
assignment.

Flow position:
  Evidence → SituationState → Incidents → Priority → Action → **Outcome**
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, Field, field_validator, model_validator


class ActionStatus(StrEnum):
    """Lifecycle status of a dispatch decision."""

    PENDING = "pending"           # Decision made, not yet executed
    IN_PROGRESS = "in_progress"   # Resource is actively responding
    DONE = "done"                 # Action completed; outcome to be recorded
    FAILED = "failed"             # Action could not be completed
    CANCELLED = "cancelled"       # Decision overridden before execution


class Action(BaseModel):
    """A decision to assign one resource to one incident.

    ``decision_rationale`` is a plain-text explanation.  In V1 this is
    generated by rule-based logic; in V2 it can be LLM-generated.  The field
    is always required so that every decision is explainable.

    ``priority`` is an integer rank within the current dispatch queue
    (1 = highest priority).  Two actions may share the same priority value;
    the planner may break ties however it chooses.

    Example::

        action = Action(
            incident_id="<uuid>",
            resource_id="<uuid>",
            decided_by="rule_engine_v1",
            decision_rationale="Highest risk_score zone; only available pump nearby.",
            priority=1,
        )
    """

    # ── identity ──────────────────────────────────────────────────────────
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))

    # ── links ─────────────────────────────────────────────────────────────
    incident_id: str = Field(
        ...,
        min_length=1,
        description="ID of the Incident this action addresses.",
    )
    resource_id: str = Field(
        ...,
        min_length=1,
        description="ID of the Resource being deployed.",
    )

    # ── decision metadata ─────────────────────────────────────────────────
    decided_by: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Identifier of the agent/system/user that made the decision.",
    )
    decision_rationale: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Human-readable explanation for this assignment.",
    )
    priority: int = Field(
        default=1,
        ge=1,
        description="Dispatch priority rank (1 = most urgent).",
    )

    # ── lifecycle ─────────────────────────────────────────────────────────
    status: ActionStatus = Field(default=ActionStatus.PENDING)
    decided_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    started_at: datetime | None = Field(default=None)
    completed_at: datetime | None = Field(default=None)

    # ── validators ────────────────────────────────────────────────────────

    @field_validator("incident_id", "resource_id", "decided_by", mode="before")
    @classmethod
    def strip_strings(cls, v: object) -> object:
        if isinstance(v, str):
            return v.strip()
        return v

    @model_validator(mode="after")
    def completed_at_requires_terminal_status(self) -> Action:
        terminal = {ActionStatus.DONE, ActionStatus.FAILED, ActionStatus.CANCELLED}
        if self.completed_at is not None and self.status not in terminal:
            raise ValueError(
                "completed_at may only be set when status is DONE, FAILED, or CANCELLED."
            )
        return self

    @model_validator(mode="after")
    def started_at_ordering(self) -> Action:
        if self.started_at and self.completed_at:
            if self.started_at > self.completed_at:
                raise ValueError("started_at must not be after completed_at.")
        return self

    model_config = {"frozen": False, "extra": "forbid"}
